### ISSUE TITLE
No idea how to find the problem

### ISSUE THREAD

**Issue by ftomassetti** [witspirit/IntelliJBehave#27]
When I run my tests and I have a failure I just get a verbose output (hundreds of lines) and I have no which tests is failing or why

**Comment by mrge-org** [comment]
Hi, do you have output file to open in a browser and see the same content as the input document but with the tags highlighted in green or red?

**Comment by matozoid** [comment]
Hello, I have the same problem. I don't understand what you are asking?

**Comment by mrge-org** [comment]
Never mind - I was thinking about different repo when writing this answer. My fault.

**Comment by picimako** [comment]
Closing as the issue seems no longer relevant.
