### ISSUE TITLE
Add support for Kotlin

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [witspirit/IntelliJBehave#32]
Hi, I added support for Kotlin to this project some weeks ago, so I would like you to accept my contribution. :)

**Comment by RodrigoQuesadaDev** [comment]
Here is the PR: https://github.com/witspirit/IntelliJBehave/pull/33

This PR should also make the plugin available for Android Studio: https://plugins.jetbrains.com/?androidstudio (currently is not being displayed as compatible with it, which it is)

**Comment by RodrigoQuesadaDev** [comment]
Changes to your code are minimal, I only changed StepDefinitionIterator.java and JBehaveStepsIndex.java files, and added some Kotlin files whose code is conditionally executed depending on whether or not Kotlin plugin is installed (*if (KotlinConfigKt.getPluginIsEnabled()*) {).

**Comment by JenoDK** [comment]
Changes have been merged into master and also in version v1.53
