### ISSUE TITLE
Step parameters are not highlighted in Intellij Idea 2016.2

### ISSUE THREAD

**Issue by ilzul** [witspirit/IntelliJBehave#38]
Hi,

The step parameters are not highlighted in Intellij Idea v.2016.2.
This feature works fine with Intellij Idea v.15.0.6.

Could someone have a look ?

Thanks

**Comment by Eernie** [comment]
+1

**Comment by stefanschenk** [comment]
I forked this repository in which I fixed the highlighting for parameters.
See [https://github.com/stefanschenk/IntelliJBehave](https://github.com/stefanschenk/IntelliJBehave)

I've released a [version 1.6](https://github.com/stefanschenk/IntelliJBehave/releases/tag/v1.6) which only works from IntelliJ IDEA 2016.1 and up

**Comment by harley84** [comment]
@stefanschenk , thanks for keeping this old project alive. If you create a pull request I'll merge it to here and will release your version for everyone to enjoy
