### ISSUE TITLE
IntelliJ Idea getting stuck when the plugin is enabled

### ISSUE THREAD

**Issue by isharasampath** [witspirit/IntelliJBehave#41]
Plugin v1.52

We have nearly **400 story** files having more than **1 million lines**. Once we enabled the plugin and after few seconds IntelliJ Idea will be stuck and we'll have to kill the process and restart the IDE. But then again it happens until disable the plugin.

This has been a huge issue for us and about 30 automation engineers are blocked. Looking for an immediate solution.

**Comment by harley84** [comment]
Having more than 1 million lines in total or in each file?
In any case, the plugin needs to index the code in order to work so I suggest giving it time.
Other than that, this project is open source and free and you're welcome to contribute any performance improvements to the community.

**Comment by JenoDK** [comment]
Hi @isharasampath , could this by any chance be the same issue as this [one](https://github.com/witspirit/IntelliJBehave/issues/46)?

**Comment by isharasampath** [comment]
@JenoDK  Thanks for information. Yes, this is the issue I was facing and happy to see that it's fixed. Great job!
